### ISSUE TITLE
Consider always enabling "check" for debug builds?

### ISSUE THREAD

**Issue by qinsoon** [dovahcrow/peace-lock#3]
The ideal use for the crate would be enabling "check" for debug builds so that we know there is any race, and disabling it for release for better performance. However, due to cargo's limitation, it is not possible to activate a feature for dependency crates based on the build. 

An alternative solution would be using something like `#[cfg(any(debug_assertions, feature = "check"))]` instead of `#[cfg(feature = "check")]` in the code to guard the checks. In that case, the checks will always be included in a debug build, and can be optionally included in a release build.

If you think this sounds reasonable, I can submit a PR for the changes.

**Comment by dovahcrow** [comment]
This is an excellent idea indeed! Please create the PR!

**Comment by dovahcrow** [comment]
Thank you!
